# Generated by Django 2.2.3 on 2019-07-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
